In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
df = pd.read_csv(r'C:\Users\Rameshwar Agarwal\Desktop\python\assignment 14\bio-degradabale-data.csv', delimiter=';', header=None)

In [8]:
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,3.919,2.6909,0,0,0,0,0,31.4,2,0,...,0,0,0,2.949,1.591,0,7.253,0,0,RB
1,4.170,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,3.315,1.967,0,7.257,0,0,RB
2,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,1,3.076,2.417,0,7.601,0,0,RB
3,3.000,2.7098,0,0,0,0,0,20.0,0,2,...,0,0,1,3.046,5.000,0,6.690,0,0,RB
4,4.236,3.3944,0,0,0,0,0,29.4,2,4,...,0,0,0,3.351,2.405,0,8.003,0,0,RB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,5.431,2.8955,0,0,0,2,0,32.1,4,1,...,0,6,1,3.573,2.242,1,8.088,0,0,NRB
1051,5.287,3.3732,0,0,9,0,0,35.3,0,9,...,0,3,0,3.787,3.083,3,9.278,0,0,NRB
1052,4.869,1.7670,0,1,9,0,5,44.4,0,4,...,4,13,0,3.848,2.576,5,9.537,1,0,NRB
1053,5.158,1.6914,2,0,36,0,9,56.1,0,0,...,1,16,0,5.808,2.055,8,11.055,0,1,NRB
1054,5.076,2.6588,2,0,0,0,4,54.5,0,0,...,2,0,0,4.009,2.206,0,9.130,0,2,NRB

In [9]:
X=df.iloc[:, 0:41]
y=df.iloc[:, 41]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test= train_test_split(X,y,test_size=0.2)

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

fit_tree = tree.fit(X_train, y_train)

predict = tree.predict(X_test)

from sklearn import metrics
print(metrics.accuracy_score(predict,y_test))

from sklearn.model_selection import cross_val_score
print(cross_val_score(fit_tree, X, y, cv=5, scoring='accuracy').mean())

0.7962085308056872
0.8018957345971565

In [13]:
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1))

abc.fit(X_train, y_train)

predict = abc.predict(X_test)

print(metrics.accuracy_score(predict, y_test))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

0.8388625592417062